Validate checksums and version number in automated release CI (#4564)
* add release version checks

* set exit

* dummy 7.7.7 release version

* explicit verify of checksums

* cd into correct dir

* need conda for testing

* syntax

* break apart steps a bit

* set path to environment

* bad path :(

* bad path again :(

* dont build tests

* check installed version version

* use pdal-config for clean version string

* only release for x.x.x

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,7 +15,7 @@ concurrency:
 jobs:
 
   build:
-    name: Configure source tree
+    name: Package ${{ github.ref_name }} release
     defaults:
       run:
         shell: bash -l {0}
@@ -67,10 +67,74 @@ jobs:
         path: |
          ./build/PDAL*
 
-  release:
-    name: Gather and attach release
+  test:
+    name: Test ${{ github.ref_name }} release
     runs-on: ubuntu-latest
     needs: build
+    permissions:
+      contents: write
+    steps:
+     - uses: actions/download-artifact@v4
+       name: Download release artifact
+       with:
+         name: source-package-ubuntu-latest
+         path: release
+
+     - name: Verify checksums
+       shell: bash -l {0}
+       working-directory: ./release
+       run: |
+          set -e
+          sha256sum -c *.sha256sum
+
+
+     - name: Unzip
+       shell: bash -l {0}
+       working-directory: ./release
+       run: |
+          set -e
+          echo "Tagged version is $GITHUB_REF_NAME, checking that PDAL version is the same"
+          ls *
+          tar xvf PDAL-${{ github.ref_name }}-src.tar.bz2
+          cd PDAL-$GITHUB_REF_NAME-src
+
+     - uses: mamba-org/setup-micromamba@v2
+       name: Install mamba
+       with:
+         init-shell: bash
+         environment-file: "./release/PDAL-${{ github.ref_name }}-src/scripts/ci/current-environment.yml"
+         environment-name: "pdal-build"
+         cache-environment: true
+         cache-downloads: true
+
+     - name: Confirm release
+       shell: bash -l {0}
+       working-directory: ./release/PDAL-${{ github.ref_name }}-src
+       run: |
+          set -e
+          source ./scripts/ci/linux/setup.sh
+          cd build
+          source ../scripts/ci/linux/cmake.sh
+          cmake .. \
+            -G Ninja \
+            -DCMAKE_LIBRARY_PATH:FILEPATH="$CONDA_PREFIX/lib" \
+            -DCMAKE_INCLUDE_PATH:FILEPATH="$CONDA_PREFIX/include" \
+            -DCMAKE_BUILD_TYPE=Release \
+            -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
+            -DWITH_TESTS=OFF
+          source ../scripts/ci/linux/compile.sh
+          export PDAL_VERSION=$(pdal-config --version)
+          if [ $GITHUB_REF_NAME == $PDAL_VERSION ]; then
+            echo "Tagged version equals tree version. All good."
+          else
+            echo "Tagged version is $GITHUB_REF_NAME and PDAL version is $PDAL_VERSION. Failing"
+            exit 1;
+          fi
+
+  release:
+    name: Gather ${{ github.ref_name }} release
+    runs-on: ubuntu-latest
+    needs: test
     permissions:
       contents: write
     steps:
