add release version checks

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,8 +5,8 @@ on:
 
     # only publish draft for x.x.x tags
     tags:
-#      - '**' # for testing
-      - "[0-9]+.[0-9]+.[0-9]+"
+      - '**' # for testing
+#      - "[0-9]+.[0-9]+.[0-9]+"
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
@@ -15,7 +15,7 @@ concurrency:
 jobs:
 
   build:
-    name: Configure source tree
+    name: Package ${{ github.ref_name }} release
     defaults:
       run:
         shell: bash -l {0}
@@ -67,10 +67,43 @@ jobs:
         path: |
          ./build/PDAL*
 
-  release:
-    name: Gather and attach release
+  test:
+    name: Test ${{ github.ref_name }} release
     runs-on: ubuntu-latest
     needs: build
+    permissions:
+      contents: write
+    steps:
+     - uses: actions/download-artifact@v4
+       name: Download release artifact
+       with:
+         name: source-package-ubuntu-latest
+         path: release
+
+     - name: Unzip
+       shell: bash -l {0}
+       working-directory: ./release
+       run: |
+          ls *
+          sha256sum -c PDAL-$GITHUB_REF_NAME-src.tar.gz.sha256sum
+          tar xvf PDAL-${{ github.ref_name }}-src.tar.bz2
+          cd PDAL-$GITHUB_REF_NAME
+          source ./scripts/ci/linux/setup.sh
+          cd build
+          source ../scripts/ci/linux/cmake.sh
+          source ../scripts/ci/linux/compile.sh
+          export PDAL_VERSION=./build/bin/pdal --version
+          if [ $GITHUB_REF_NAME == $PDAL_VERSION ]; then
+            echo "Tagged version equals tree version. All good."
+          else
+            echo "Tagged version is $GITHUB_REF_NAME and PDAL version is $PDAL_VERSION. Failing"
+            exit 1;
+          fi
+
+  release:
+    name: Gather ${{ github.ref_name }} release
+    runs-on: ubuntu-latest
+    needs: test
     permissions:
       contents: write
     steps:
